# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="af-magic"

plugins=(git gitfast gulp history-substring-search vagrant gradle fzf)

# User configuration
# Check if neovim, ripgrep, cargo, python3, and pip3 are installed
if [ -x "$(command -v go)" ]; then
    export GOPATH=$HOME/go
    export PATH=$PATH:$(go env GOPATH)/bin
fi

export PATH=$PATH:"/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

source $ZSH/oh-my-zsh.sh
