# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="af-magic"

plugins=(git gitfast gulp history-substring-search vagrant gradle)

# User configuration
export GOPATH=$HOME/go
export PATH=$PATH:"/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH=$PATH:$(go env GOPATH)/bin

source $ZSH/oh-my-zsh.sh

